name: Deploy to Google AI Studio
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v5 # Pakai v5 agar tidak error Node 20
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install
      - run: npm run build --if-present
      - uses: actions/upload-artifact@v5 # Pakai v5
        with:
          name: app-dist
          path: .
