name: Deploy to Google AI Studio
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4 # Gunakan v4 untuk support Node 20+
        with:
          node-version: '20'
      # Tambahkan step build Anda di sini
